# Generated by Django 4.0.6 on 2022-07-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssestManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssestId', models.CharField(max_length=250)),
                ('Symbol', models.CharField(blank=True, max_length=250)),
                ('Name', models.CharField(blank=True, max_length=250)),
                ('ThumbImage', models.CharField(blank=True, max_length=250)),
                ('SmallImage', models.CharField(blank=True, max_length=250)),
                ('LargeImage', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
