# Generated by Django 4.0.6 on 2022-07-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoinApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssestDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssestId', models.CharField(max_length=250)),
            ],
        ),
    ]
