# Generated by Django 4.0.6 on 2022-07-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoinApi', '0002_assestdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assestdetail',
            name='AssestId',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='assestmanager',
            name='AssestId',
            field=models.UUIDField(),
        ),
    ]
