# Generated by Django 4.0.6 on 2022-08-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoinApi', '0003_alter_assestdetail_assestid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assestdetail',
            name='AssestId',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='assestmanager',
            name='AssestId',
            field=models.CharField(max_length=250),
        ),
    ]
