# Generated by Django 4.0.6 on 2022-07-27 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_usermodel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='id',
            new_name='Id',
        ),
    ]
